global:
// Define a frequência com que o Prometheus coleta métricas de todos os targets configurados. No caso, a cada 15 segundos.
  scrape_interval: 15s
  Define a frequência com que o Prometheus avalia as regras. Também está configurado para a cada 15 segundos.
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_app"
    static_configs:
      - targets: ["localhost:3003"]

  - job_name: "deploy_status"
    static_configs:
      - targets: ["192.168.200.253:9091"]
